PROMPT='[%F{green}%n%f%F{cyan}@%f%F{yellow}%m%f %F{red}❤️%f %F{cyan}%~%f] %F{red}%(!.#.$)%f '
RPROMPT='%(?.%F{green}√%f.%F{yellow}⚠️ %?%f) [%*]'

# history
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=1000000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS

# directory stack
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS

# completion
autoload -Uz compinit; compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

# vi mode
bindkey -v
export KEYTIMEOUT=1
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line

# plugins
[[ -f $ZSH_PLUGIN_HOME/z/z.sh ]] && source $ZSH_PLUGIN_HOME/z/z.sh

[[ -f $ZSH_PLUGIN_HOME/zsh-autosuggestions/zsh-autosuggestions.zsh ]] &&
    source $ZSH_PLUGIN_HOME/zsh-autosuggestions/zsh-autosuggestions.zsh

[[ -f $ZSH_PLUGIN_HOME/zsh-completions/zsh-completions.zsh ]] &&
    source $ZSH_PLUGIN_HOME/zsh-completions/zsh-completions.zsh

[[ -f $ZSH_PLUGIN_HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] &&
    source $ZSH_PLUGIN_HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ -f $ZSH_PLUGIN_HOME/zsh-history-substring-search/zsh-history-substring-search.zsh ]]; then
    source $ZSH_PLUGIN_HOME/zsh-history-substring-search/zsh-history-substring-search.zsh
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
fi

# ruby
if [[ -x "$(command -v ruby)" ]]; then
    export GEM_HOME=$HOME/.gem
    export PATH=$GEM_HOME/bin:$PATH
fi
